### ISSUE TITLE
Add Util Packages to Knit's wally version

### ISSUE THREAD

**Issue by Biack1st** [Sleitnick/Knit#206]
_This is my first issue so I apologize if it's unprofessional._ 

As of writing this, the wally version of knit doesn't include Util's packages. For example if you try to do this using the  wally version of knit, it'll error:

```lua
local ReplicatedStorage = game:GetService("ReplicatedStorage")

local knit = require(ReplicatedStorage.Packages.Knit)

require(knit.Util.Component) -- errors here with an attempt to index nil error.
```

This is not an issue with just the Component util, but all of them. 

Of course with some util packages you can simply add them to your `wally.toml` file. But there are some packages which are exclusive to the Knit's Util(to my knowledge).  But it also lowers developer productivity as they'd have to find the Util package and add it to the `wally.toml` file.

If the util packages were added to Knit's Wally version it would greatly enhance me and many more developer's experiences with Knit.

Thanks for reading.

**Comment by eAi** [comment]
I think (and I may well be wrong) that this is as expected. If you want your project to depend on a package that a package you use depends on, you should add it to your wally.toml file. Otherwise you’re depending on an implementation detail of how Knit works which could change at any point. Equally you may want to use a different version of the same package - which I believe wally will let co-exist (though there may be unexpected consequences with this in some cases)

**Comment by eAi** [comment]
Also, Knit only depends on one Util - Comm, and it certainly should include all the others just for convenience sake - but maybe I’m misunderstanding you?

**Comment by Sleitnick** [comment]
Yeah, this is by design. You can add any of those utility packages to your own wally file (those util modules are here: https://github.com/Sleitnick/RbxUtil).

The future of Knit is going to move entirely away from exposing a Util folder too, but that's for a future v2.
