### ISSUE TITLE
Allowing Thread.DelayRepeat to connect immediately rather than yield

### ISSUE THREAD

**Issue by CaptinLetus** [Sleitnick/Knit#27]
Currently with Thread.Delay, the function will always yield for the intervalTime before connecting to the heartbeat.  Having the option to connect to the heartbeat immediately would allow the function to be useful in more use-cases.

# My proposed solution
```lua
function Thread.DelayRepeat(intervalTime, func, yieldMethod, ...)
    local args = table.pack(...)
    local nextExecuteTime
    yieldMethod = yieldMethod or "before"
    assert(yieldMethod == "before" or yieldMethod == "after", "yieldMethod must be \"before\" or \"after\"")
    
    if yieldMethod == "before" then
        nextExecuteTime = (time() + intervalTime)
    elseif yieldMethod == "after" then
        nextExecuteTime = 0
    end

    local hb
    hb = heartbeat:Connect(function()
        if (time() >= nextExecuteTime) then
            nextExecuteTime = (time() + intervalTime)
            func(table.unpack(args, 1, args.n))
        end
    end)
    return hb
end```

**Comment by Sleitnick** [comment]
I've actually run into needing this a few times recently. The reason I haven't immediately implemented a change like this is due to backwards-compatibility: By adding a third argument before the 'varargs' `...`, it could mess up existing code that relies on passing those arguments.

_However_, considering Knit is still in alpha, this is the exact time in its lifespan to make breaking changes. I think there's a good reason to add something like this.

I would prefer to stay away from using string values to indicate behavior though. Instead, we could do something where `yieldMethod` is renamed to something like `immediateExecution` (or something less verbose), and is just a boolean `true|false`.

**Comment by Sleitnick** [comment]
@CaptinLetus Made a PR for this. Let me know what you think: https://github.com/Sleitnick/Knit/pull/28/files#diff-da7f058710b3a2b5b96e5ee4d6367fa53f143f6b3c5fcc3c48c7da783fa32045R151

**Comment by CaptinLetus** [comment]
A much cleaner implementation that my own to accomplish the same result.  The only 2 possible yieldMethod in my solution are before and after so a boolean makes perfect sense here.  Looks great!
